In [1]:
import numpy as np
import matplotlib.pylab as plt

## Problema 1

In [2]:
#b)
M = np.array([[4, -1, -1, -1],
             [-1, 3, 0, -1],
             [-1, 0, 3, -1],
             [-1, -1, -1, 4]], float)
v = np.array([5, 0, 5, 0], float)
N = len(v)
sol = np.zeros(N)

In [3]:
for i in range(N):
    print(M)
    v[i] = v[i]/M[i,i]
    M[i,:] = M[i,:]/M[i,i]
    
    for j in range(i+1,N):
        mult = -(M[j,i])
        M[j,:] = M[j,:] + mult*M[i,:]
        v[j] = v[j] + mult*v[i]
print(M)
print(v)

for i in range(N-1,-1,-1):
    sol[i] = v[i]
    for j in range(i+1,N):
        sol[i] -= M[i,j]*sol[j] 

[[ 4. -1. -1. -1.]
 [-1.  3.  0. -1.]
 [-1.  0.  3. -1.]
 [-1. -1. -1.  4.]]
[[ 1.   -0.25 -0.25 -0.25]
 [ 0.    2.75 -0.25 -1.25]
 [ 0.   -0.25  2.75 -1.25]
 [ 0.   -1.25 -1.25  3.75]]
[[ 1.         -0.25       -0.25       -0.25      ]
 [ 0.          1.         -0.09090909 -0.45454545]
 [ 0.          0.          2.72727273 -1.36363636]
 [ 0.          0.         -1.36363636  3.18181818]]
[[ 1.         -0.25       -0.25       -0.25      ]
 [ 0.          1.         -0.09090909 -0.45454545]
 [ 0.          0.          1.         -0.5       ]
 [ 0.          0.          0.          2.5       ]]
[[ 1.         -0.25       -0.25       -0.25      ]
 [ 0.          1.         -0.09090909 -0.45454545]
 [ 0.          0.          1.         -0.5       ]
 [ 0.          0.          0.          1.        ]]
[1.25       0.45454545 2.33333333 2.        ]


In [4]:
sol

array([3.        , 1.66666667, 3.33333333, 2.        ])

In [5]:
#c)
np.linalg.solve(M, v)

array([3.        , 1.66666667, 3.33333333, 2.        ])

Dessa forma, da para ver que o código está correto

## Problema 2

In [6]:
#a)
#primeiro sistema
M = np.array([[2, 1, 4, 1],
             [3, 4, -1, -1],
             [1, -4, 1, 5],
             [2, -2, 1, 3]], float)
v = np.array([-4, 3, 9, 7], float)
N = len(v)
sol = np.zeros(N)

In [7]:
for i in range(N):
    print(M)
    v[i] = v[i]/M[i,i]
    M[i,:] = M[i,:]/M[i,i]
    
    for j in range(i+1,N):
        mult = -(M[j,i])
        M[j,:] = M[j,:] + mult*M[i,:]
        v[j] = v[j] + mult*v[i]
print(M)
print(v)

for i in range(N-1,-1,-1):
    sol[i] = v[i]
    for j in range(i+1,N):
        sol[i] -= M[i,j]*sol[j] 

[[ 2.  1.  4.  1.]
 [ 3.  4. -1. -1.]
 [ 1. -4.  1.  5.]
 [ 2. -2.  1.  3.]]
[[ 1.   0.5  2.   0.5]
 [ 0.   2.5 -7.  -2.5]
 [ 0.  -4.5 -1.   4.5]
 [ 0.  -3.  -3.   2. ]]
[[  1.    0.5   2.    0.5]
 [  0.    1.   -2.8  -1. ]
 [  0.    0.  -13.6   0. ]
 [  0.    0.  -11.4  -1. ]]
[[ 1.   0.5  2.   0.5]
 [ 0.   1.  -2.8 -1. ]
 [-0.  -0.   1.  -0. ]
 [ 0.   0.   0.  -1. ]]
[[ 1.   0.5  2.   0.5]
 [ 0.   1.  -2.8 -1. ]
 [-0.  -0.   1.  -0. ]
 [-0.  -0.  -0.   1. ]]
[-2.   3.6 -2.   1. ]


In [8]:
print("Solução para o primeiro sistema", sol)

Solução para o primeiro sistema [ 2. -1. -2.  1.]


In [9]:
#segundo sistema
M = np.array([[0, 1, 4, 1],
             [3, 4, -1, -1],
             [1, -4, 1, 5],
             [2, -2, 1, 3]], float)

v = np.array([-4, 3, 9, 7], float)
N = len(v)
sol = np.zeros(N)

In [10]:
for i in range(N):
    print(M)
    if(M[i,i]==0):
        
        temp2 = 0
        for q in range(N):
            if(temp2<abs(M[q,i])):
                temp2 = M[q, i]
                t = q
        for j in range(N):        
            temp=M[t,j]    
            M[t, j] = M[i, j]
            M[i,j] = temp
        
        temp = v[i]
        v[i]=v[t]
        v[t] = temp
        print(M)
        
    v[i] = v[i]/M[i,i]
    M[i,:] = M[i,:]/M[i,i]
        
        
    for j in range(i+1,N):
        mult = -(M[j,i])
        M[j,:] = M[j,:] + mult*M[i,:]
        v[j] = v[j] + mult*v[i]
print(M)
print(v)

for i in range(N-1,-1,-1):
    sol[i] = v[i]
    for j in range(i+1,N):
        sol[i] -= M[i,j]*sol[j] 

[[ 0.  1.  4.  1.]
 [ 3.  4. -1. -1.]
 [ 1. -4.  1.  5.]
 [ 2. -2.  1.  3.]]
[[ 3.  4. -1. -1.]
 [ 0.  1.  4.  1.]
 [ 1. -4.  1.  5.]
 [ 2. -2.  1.  3.]]
[[ 1.          1.33333333 -0.33333333 -0.33333333]
 [ 0.          1.          4.          1.        ]
 [ 0.         -5.33333333  1.33333333  5.33333333]
 [ 0.         -4.66666667  1.66666667  3.66666667]]
[[ 1.          1.33333333 -0.33333333 -0.33333333]
 [ 0.          1.          4.          1.        ]
 [ 0.          0.         22.66666667 10.66666667]
 [ 0.          0.         20.33333333  8.33333333]]
[[ 1.          1.33333333 -0.33333333 -0.33333333]
 [ 0.          1.          4.          1.        ]
 [ 0.          0.          1.          0.47058824]
 [ 0.          0.          0.         -1.23529412]]
[[ 1.          1.33333333 -0.33333333 -0.33333333]
 [ 0.          1.          4.          1.        ]
 [ 0.          0.          1.          0.47058824]
 [-0.         -0.         -0.          1.        ]]
[ 1.         -4.         -

In [11]:
sol

array([ 1.61904762, -0.42857143, -1.23809524,  1.38095238])

In [12]:
np.linalg.solve(M, v)

array([ 1.61904762, -0.42857143, -1.23809524,  1.38095238])

## Problema 3

In [13]:
M = np.array([[2, 1, 4, 1],
             [3, 4, -1, -1],
             [1, -4, 1, 5],
             [2, -2, 1, 3]], float)
v = np.array([-4, 3, 9, 7])

In [14]:
#a)

N = len(M)
L = np.zeros((N,N))
cont = 0
    
for i in range(N):
    print(M)
    for j in range(cont,N):
        L[j][i] = M[j][i]
            
    M[i,:] = M[i,:]/M[i,i]

    for j in range(i+1,N):
        mult = -(M[j,i])
        M[j,:] = M[j,:] + mult*M[i,:]
            
    cont = cont + 1
U = M
#Multiplicando L por U
ori = np.zeros((N,N))
    
for i in range(N):
    for j in range(N):
        temp = 0
        for k in range(N):
                temp = temp +  L[i][k]*U[k][j]
                ori[i][j] = temp
U, L, ori

[[ 2.  1.  4.  1.]
 [ 3.  4. -1. -1.]
 [ 1. -4.  1.  5.]
 [ 2. -2.  1.  3.]]
[[ 1.   0.5  2.   0.5]
 [ 0.   2.5 -7.  -2.5]
 [ 0.  -4.5 -1.   4.5]
 [ 0.  -3.  -3.   2. ]]
[[  1.    0.5   2.    0.5]
 [  0.    1.   -2.8  -1. ]
 [  0.    0.  -13.6   0. ]
 [  0.    0.  -11.4  -1. ]]
[[ 1.   0.5  2.   0.5]
 [ 0.   1.  -2.8 -1. ]
 [-0.  -0.   1.  -0. ]
 [ 0.   0.   0.  -1. ]]


(array([[ 1. ,  0.5,  2. ,  0.5],
        [ 0. ,  1. , -2.8, -1. ],
        [-0. , -0. ,  1. , -0. ],
        [-0. , -0. , -0. ,  1. ]]),
 array([[  2. ,   0. ,   0. ,   0. ],
        [  3. ,   2.5,   0. ,   0. ],
        [  1. ,  -4.5, -13.6,   0. ],
        [  2. ,  -3. , -11.4,  -1. ]]),
 array([[ 2.,  1.,  4.,  1.],
        [ 3.,  4., -1., -1.],
        [ 1., -4.,  1.,  5.],
        [ 2., -2.,  1.,  3.]]))

In [15]:
#b)
v = np.array([-4, 3, 9, 7])
y = np.zeros(N)

for k in range(N):
    y[k] = v[k]/L[k][k]
    for q in range(k-1, -1, -1):
        y[k] = y[k] - (L[k][q]*y[q])/L[k][k]
y

array([-2. ,  3.6, -2. ,  1. ])

In [16]:
x = np.zeros(N)
for k in range(N-1, -1, -1):
    x[k] = y[k]
    for q in range(k+1, N):
        x[k] = x[k] - M[k][q]*x[q]
x

array([ 2., -1., -2.,  1.])

In [17]:
np.linalg.solve(L,v), np.linalg.solve(M, y)

(array([-2. ,  3.6, -2. ,  1. ]), array([ 2., -1., -2.,  1.]))